# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: "Be concise and focus on critical issues only"
early_access: false
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  poem: false
  review_status: true
  collapse_walkthrough: false

  # Keep reviews focused on source
  path_filters:
    - "src/**"

  # Reviewer guidance (no blocking gates here)
  path_instructions:
    - path: "src/main/java/**"
      instructions: |
        nl.blitz.oop.math exercise — apply these during review:

        • Package hygiene
          - All classes declare: package nl.blitz.oop.math;

        • Files / Classes
          - Ensure files exist:
              src/main/java/nl/blitz/oop/math/Calculator.java
              src/main/java/nl/blitz/oop/math/Demo.java
          - Calculator.java declares: public class Calculator
          - Demo.java declares: public class Demo with public static void main(String[] args)

        • Method Overloading (compile-time polymorphism)
          - Calculator must declare these overloads:
              1) public int add(int, int)
              2) public double add(double, double)
              3) public int add(int...)
          - Signatures must differ by parameter types/arity (not only return type)

        • Validation
          - add(int... nums) must validate that at least one argument is provided
            and throw IllegalArgumentException if none

        • Implementation
          - Method bodies must be implemented and return computed results
          - Methods should NOT throw UnsupportedOperationException

        • No public mutable state
          - No public fields
          - No mutable state exposed publicly

        • Demo behavior
          - Demo.main instantiates Calculator
          - Calls each overload with sample values and prints results

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "wip"
      - "draft"
    labels: []
    drafts: false
    base_branches: []

pre_merge_checks:
  title:
    mode: warning
    requirements: "Title should be concise and descriptive"
  description:
    mode: warning
  issue_assessment:
    mode: warning
  custom_checks:
    - mode: error
      name: "Files exist"
      instructions: >
        Fail if Calculator.java is not at src/main/java/nl/blitz/oop/math/Calculator.java,
        or if Demo.java is not at src/main/java/nl/blitz/oop/math/Demo.java.

    - mode: error
      name: "Package hygiene"
      instructions: >
        Fail if Calculator.java or Demo.java does not declare 'package nl.blitz.oop.math;'.

    - mode: error
      name: "Overload signatures"
      instructions: >
        Fail if Calculator does not contain all of:
        - 'public int add(int, int)'
        - 'public double add(double, double)'
        - 'public int add(int...)'

    - mode: error
      name: "Varargs validation"
      instructions: >
        Fail if add(int...) does not check that at least one argument was provided and
        throw IllegalArgumentException when none are given.

    - mode: error
      name: "Method implementation"
      instructions: >
        Fail if any add overload throws UnsupportedOperationException or is missing a return.
        Methods must compute and return sums appropriate to their signatures.

    - mode: error
      name: "Demo exercises overloads"
      instructions: >
        Fail if Demo.main does not instantiate Calculator and call each overload with sample values,
        printing results. Allow any variable names and print styles.

tools:
  github-checks:
    enabled: true
    timeout_ms: 90000
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  gitleaks:
    enabled: true

  # Optional static analyzers (kept enabled, but not required for gating)
  pmd:
    enabled: true
  semgrep:
    enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/.cursorrules"
      - "**/CODING_STANDARDS.md"

code_generation:
  docstrings:
    language: en-US
  unit_tests:
    path_instructions: []

